### ISSUE TITLE
[8.0][web_m2x_options] m2o pop up selection hide result > 80

### ISSUE THREAD

**Issue by legalsylvain** [OCA/web#1123]
Step to reproduce : 
- go to runbot OCA/web/8.0
- install point_of_sale (to have data populated)
- go to invoicing, and create a new invoice
- select a product and click on "search more"
- the pop up screen mentions that there are only 80 elements

![image](https://user-images.githubusercontent.com/3407482/49582548-b6403e00-f955-11e8-937f-e5093e97040a.png)

- uninstall the module web_m2x_options. 
- refresh the cache
-> the behaviour of the pop up is now ok 

![image](https://user-images.githubusercontent.com/3407482/49582682-18993e80-f956-11e8-9ecc-0839f700f177.png)

version 8 : :-1: impacted
version 9 : :question: not tested
version 10.0 : :question:  not tested
version 11.0 : :+1: OK 

CC : authors : @hbrunn, @njeudy, @yvaucher, @Yajo, @chienandalu ....

**Comment by Boudmir-Ibrahim** [comment]
Hi @legalsylvain,
I have already mentioned this and @pedrobaeza 's answer was closing it due to Design decision. And i actually do agree!
i quote him : " This has been reported other times and it's done on purpose for avoiding an excessive load for a refining operation that is intended. When you change default filter is when then the limit is removed. Although it can result confusing, it's not important once you know the reason."

I have about 15000 records. removing the limit would force to load all of them which will certainly slow down heavily the process..

**Comment by legalsylvain** [comment]
Hi @boudmir-ibrahim 

- this bug has been fixed 2 monthes ago
- as said in the fix, it works well for médium sized database (~50k production)

**Comment by Boudmir-Ibrahim** [comment]
This issue must be closed then.

**Comment by pedrobaeza** [comment]
Note that the restriction is applied by Odoo itself, and it was done on purpose, where loading full recordset there involved a costly operation on all records (`name_get` if I don't remember bad), and it's still limited in latest versions for initial load when clicking on "Search more...". If you press enter again in the search bar, then full load is performed.

The question for this issue and the fix is that the initial limit was changed from 80 to 160 from one version to another (not sure if from v7 to v8), and that limit was not reflected here. But as said by @legalsylvain, this is not made equivalent, so closing this.

**Comment by pedrobaeza** [comment]
As a curiosity, look that this feature is still conflicting in Odoo itself and requires work in core:

https://github.com/odoo/odoo/pull/31232

Here the explanation is done for the 160 limit, as it uses `name_search` method, which uses `name_get`.
