### ISSUE TITLE
[web_responsive] Display the menu when logging in instead of the communications module.

### ISSUE THREAD

**Issue by mileo** [OCA/web#1435]
Display the menu when logging in instead of the communications module.

**Comment by pedrobaeza** [comment]
I don't get what do you mean

**Comment by mileo** [comment]
When a user first accesses odoo, they may not yet have been introduced to the system interface.

So it's much more intuitive to display the application menu than the discuss module.

![image](https://user-images.githubusercontent.com/1975978/68692906-0f94f200-0555-11ea-8df9-d7d94a0fca68.png)

with web_responsive we don't have a home screen like enterprise:

![image](https://user-images.githubusercontent.com/1975978/68692856-f724d780-0554-11ea-83b2-da9039c435bb.png)

**Comment by pedrobaeza** [comment]
@Yajo @Tardo what do you think?

**Comment by Tardo** [comment]
Since you can see unread messages from systray icon i see this suggestion a good improvement.

But is not a trivial change.

**Comment by yajo** [comment]
`web_enterprise` has a specific screen for the apps selection, but `web_responsive` just extends the dropdown to make it fullscreen and behave similarly.

I consider `web_enterprise`'s approach better. One obvious advantage is that when you are using the website and hit the apps menu, you get to the same familiar screen, instead of having 2 different UIs as we have now. Another obvious advantage is what this issue is explaining.

However the change is going to be huge for `web_responsive`. Given Odoo v14 will have a completely refactored JS/Qweb system, I think we can defer this refactoring for that version.

**Comment by amachu** [comment]
What to do in web_responsive module v 12, if we have to Land users to the icons list instead of first menu in the order?

**Comment by pedrobaeza** [comment]
@amachu as said, it's difficult to be developed due to the architecture, so there's nothing you can do for that unless you develop it.

**Comment by Tardo** [comment]
This can be closed?

**Comment by pedrobaeza** [comment]
Well, the wishlist is still there. I'm not totally sure I prefer to start in the apps menu though...

**Comment by yajo** [comment]
IMHO the request is quite valid. Indeed assuming the user wants discuss after login is worse than asking him what app to open, at lest as a default behavior.



> One obvious advantage is that when you are using the website and hit the apps menu, you get to the same familiar screen, instead of having 2 different UIs as we have now.

Just to make this point clear, this is the 2nd UI I meant:

![2020-04-20_08-31](https://user-images.githubusercontent.com/973709/79727345-2e599a80-82e4-11ea-9088-8e157ce18f36.png)

Fixing this issue would let us have a more consistent UX.

In any case, IMHO we should target this for v14 at least.
