### ISSUE TITLE
web_responsive configurable per user?

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/web#1494]
Currently it's all or nothing: either all users get responsive layout, or none do. Is it feasible to add an option to have some users stay on the 'traditional' layout? Has it been tried and what would be the challenges in this?

**Comment by pedrobaeza** [comment]
No, it's technically impossible (CSS and QWeb changes), and functionally a non-sense to me. Why don't you want such interface? If you say because the side menus, it's ugly and Odoo itself has replace that by top menus.

If you want to do it, put a theme on top of web_responsive and add that possibilities, but this base module mustn't be complicated with such option that is not interesting, so closing, but if a lot of other people think it is, then I can reopen this.
