### ISSUE TITLE
Why restrict width of images? 

### ISSUE THREAD

**Issue by codingforfun** [OCA/web#1742]
module: web_tree_image_tooltip
version: 12.0

**Steps to reproduce**
- Just use the module in tree view

**Current behavior**
There is CSS code to restrict the width of the image column to 30px.
```
.o_image_cell .o_field_image img{
    width:30px;
}
```
 This overrides explicit image size settings made in the view. E.g. `<field name="image" widget="image" height="96" />`

**Expected behavior**
Only add the tooltip and don’t modify anything else in the view.

**Comment by legalsylvain** [comment]
CC : original authors : 
@nikul-serpentcs, @DonatasV

**Comment by DonatasV** [comment]
I only did one PR for this module and it's nothing to do with this `.o_image_cell .o_field_image img { width:30px; }` so I can't say why this code restrict the width of the image column.
https://github.com/OCA/web/pull/1421 - my PR limited image size, because sometimes image can be bigger than the screen

**Comment by nikul-serpentcs** [comment]
@codingforfun @legalsylvain @DonatasV 
Here We added width in version11, Because the tree view looks very ugly, [Please check ](https://github.com/OCA/web/pull/1006#issuecomment-409183102) here I already commented.

And You can check here how it works https://github.com/OCA/web/pull/1006#issuecomment-422697434.

CC @JayVora-SerpentCS

**Comment by codingforfun** [comment]
@nikul-serpentcs 
> Because the tree view looks very ugly 

Yes, but this is a matter of how the tree view is defined. 
This should be taken care of in the tree view definition itself.
For this you have `width` and `height` attributes available in the tree view definition. 
E.g.: `<field name="image" widget="image" height="32" width="32" />`

I wouldn’t expect a module that advertises to add a tool tip to implicitly alter the appearance of my view. 
This should be sliced functionality. E.g. in my use case I needed bigger images intentionally and set it using `height=48` and this module broke my view.
