### ISSUE TITLE
[14] Web responsive not showing icons and searchbar

### ISSUE THREAD

**Issue by andgit71** [OCA/web#1895]
I had mistakenly written this message in the "Migration to 14" issue. The problem remains. The module is installed on a **Debian 10** machine with **Nginx as reverse proxy**. It's a clean installation, with no modules other than the original Odoo 14 ones. All other functions of web_responsive work. The only ones that don't work are the ones that should show the icons and searchbar on the main page. Here's how the page is shown:

![image](https://user-images.githubusercontent.com/73987775/114059478-b2f64d80-9894-11eb-903c-e77d87ff0d85.png)

**Comment by pedrobaeza** [comment]
The problem is in your end, not due to the module. If you check on try me on runbot button, you will see that it's working.

**Comment by andgit71** [comment]
Sorry but I disagree. My case is a clean setup on Debian 10 and Nginx as
reverse proxy server, so a common situation. And the same problem already
occured (PR #1711 <https://github.com/OCA/web/pull/1711>).
For module installation I just added web_responsive to custom addons path,
updated apps on Odoo and installed from frontend.
I also received an error with Android smartphone:
Traceback:Error: QWeb2: Template 'web_responsive.MenuStatusbarButtons' not
found
at Object.exception (
http://erp.sintesi-erp.it/web/content/1658-3e1212c/web.assets_common.js:4388:7
)
at Engine._render (
http://erp.sintesi-erp.it/web/content/1658-3e1212c/web.assets_common.js:4433:103)

at Engine.render (
http://erp.sintesi-erp.it/web/content/1658-3e1212c/web.assets_common.js:4429:151)

at Class._renderHeaderButtons (
http://erp.sintesi-erp.it/web/content/1832-33a5621/web.assets_backend.js:6822:29)

at Class._renderHeaderButtons (
http://erp.sintesi-erp.it/web/content/1658-3e1212c/web.assets_common.js:4626:371)

at Class._renderTagHeader (
http://erp.sintesi-erp.it/web/content/1832-33a5621/web.assets_backend.js:2264:161)

at Class._renderNode (
http://erp.sintesi-erp.it/web/content/1832-33a5621/web.assets_backend.js:2255:244)

at Class._renderNode (
http://erp.sintesi-erp.it/web/content/1832-33a5621/web.assets_backend.js:5851:13)

at Class._renderNode (
http://erp.sintesi-erp.it/web/content/1658-3e1212c/web.assets_common.js:4626:371)

at Array.map (<anonymous>)

Best regards




Il giorno gio 8 apr 2021 alle ore 18:15 Pedro M. Baeza <
***@***.***> ha scritto:

**Comment by pedrobaeza** [comment]
While you don't reproduce the problem in runbot, nothing can be done.

**Comment by ypapouin** [comment]
I had this kind of issues.
The first symptom is a QWeb template not found error like you.
Using nginx error log with `debug` level enabled, I tracked down the issue to an url size limit.
I fixed it by adding this to my server nginx configuration:
```
    http2_max_field_size 8k;
    client_header_buffer_size 64k;
    large_client_header_buffers 4 64k;
```

**Comment by andgit71** [comment]
Thank you Yann. In my nginx.conf I added the suggested 3 lines under http
context and now everithing is working fine!
I suggest Pedro to add this requirement to setup instructions.

Best regards




Il giorno gio 8 apr 2021 alle ore 22:21 Yann Papouin <
***@***.***> ha scritto:

**Comment by pedrobaeza** [comment]
That's something specific of deployment, and depends on a lot of things: you can have nginx, Apache, Traefik... as reverse proxy, and then Ubuntu, Debian, Fedora, etc with their default config as OS, so this is totally out of scope of the module README.

**Comment by ypapouin** [comment]
Indeed, this is not related to this particular module, in fact it is due to the number of modules installed and their names, there is a QWeb GET query than can be a very long string.

So it depends on the fact that you are using nginx with default values, and that the size of the sum of all module's name is greater than the nginx's uri max [buffer] size. The trick here is that its impossible to understand the issue until the debug mode is enabled on the nginx error log.

If added to a documentation, it should be on the official odoo deployment:
https://www.odoo.com/documentation/12.0/setup/deploy.html#id7

Following is an example of this query on our production database:

`
https://odoo.mydomain.com/web/webclient/qweb?mods=base,web,queue_job,dbfilter_from_header,bus,web_tour,mail,calendar,sales_team,utm,contacts,auth_signup,portal,digest,crm,web_editor,website,rating,project,product,barcodes,stock,account,mrp,payment,sale,sale_management,hr,hr_timesheet,website_payment,website_mail,website_form,website_rating,website_sale,purchase,hr_attendance,account_analytic_parent,account_analytic_line_levels,account_analytic_line_sequence,base_location,account_analytic_partner_location,account_bank_statement_import,date_range,account_fiscal_year,account_invoice_line_report,account_invoice_merge,report_aeroo,res_users_signature,dec_report_aeroo,account_invoice_overdue_reminder_report_aeroo,account_partner_location,account_payment_report_aeroo,account_purchase_link,product_analytic,product_category_analytic,account_recreate_analytic_lines,account_workflow_dec,partner_fax,company_fax,account_report_aeroo,account_sale_link,account_sale_traceability,analytic_product_category,auth_admin_passkey,auth_signup_verify_email,web_responsive,backend_theme_v12,base_exception,base_export_async,base_fontawesome,base_import,base_location_cedex,base_location_count_caps,deltatech_merge,base_location_merge,base_mail_auto_copy,base_module_search,base_optional_quick_create,sequence_reset_period,base_sequence_first_number,base_technical_features,base_translation,base_url_freeze_filtering,base_xmlid,board,calendar_reservable,calendar_workflow_dec,company_report,crm_lead_action_ondrag,crm_lead_close_lost,crm_lead_partner_location,crm_lead_quick_actions,crm_location,crm_phonecall,crm_phonecall_timesheet,hr_timesheet_autofill,crm_phonecall_timesheet_autofill,project_stage_closed,hr_timesheet_task_stage,hr_timesheet_task_domain,web_ir_actions_act_view_reload,web_ir_actions_act_multi,project_timesheet_time_control,crm_timesheet,crm_timesheet_autofill,hr_timesheet_calendar,crm_timesheet_calendar,crm_timesheet_lead_context,crm_timesheet_phonecall_context,crm_timesheet_time_control,web_kanban_draggable,crm_workflow_dec,database_cleanup,google_calendar,helpdesk_mgmt,sale_stock,product_pricelist_supplierinfo,purchase_pricelist,dec,product_seller,product_report_aeroo,product_location,mrp_note,web_tree_dynamic_colored_field,stock_traceability,stock_orderpoint_move_link,stock_orderpoint_mrp_link,stock_orderpoint_purchase_link,stock_orderpoint_traceability,stock_available_unreserved,mrp_production_request,stock_mrp_traceability,mrp_traceability,stock_auto_validate,product_legacy_availability,product_small_supply,mrp_workflow_dec,mrp_picked_rate,product_pack,stock_product_pack,mrp_product_pack,mrp_report_aeroo,sale_warranty,sale_product_pack,sale_report_aeroo,stock_mrp,procurement_traceability,stock_report_aeroo,purchase_report_aeroo,dec_report_replace,delivery,deltatech_invoice_product_filter,disable_odoo_online,document,knowledge,document_page,document_page_default,mgmtsystem,document_page_work_instruction,document_page_procedure,document_page_reference,document_page_reference_auto,document_page_style,email_template_qweb,export_async_schedule,fetchmail_filtering,google_calendar_filtering,helpdesk_mgmt_project,helpdesk_mgmt_timesheet,helpdesk_notify,helpdesk_partner_location,helpdesk_references,sale_summary,helpdesk_sale,helpdesk_timesheet_autofill,helpdesk_timesheet_calendar,helpdesk_timesheet_ticket_context,helpdesk_timesheet_time_control,project_category,project_identification,helpdesk_workflow_dec,hr_org_chart,hr_timesheet_analysis,hr_timesheet_task_context,hr_timesheet_task_domain_override,hr_workflow_dec,l10n_fr,mail_activity_board,mail_activity_redirection,mail_activity_workflow_dec,mail_debrand,mail_filtering,mail_remove_gmail_signature,mail_tracking,mail_tracking_workflow,mass_operation_abstract,mass_editing,mrp_as_product,mrp_attach_picking,mrp_bom_component_menu,mrp_bom_dates,mrp_bom_order,web_widget_mermaid,product_pricelist,product_prices,mrp_bom_supplier,mrp_bom_prices,product_state_review,mrp_bom_product_state,mrp_buy_consu,mrp_bom_replace_components,mrp_change_bom,stock_mts_mto_rule,mrp_mts_mto,mrp_partner,mrp_partner_location,mrp_produce_empty,mrp_production_consume,mrp_production_consume_location,mrp_production_request_all,sale_mrp_production_request_link,mrp_production_request_partner,mrp_production_request_procurement,subcontracted_service,mrp_production_service,mrp_product_link,mrp_product_manufacturable,mrp_project,sale_mrp_link,mrp_sale,mrp_project_auto,purchase_subcontracted_service,mrp_purchase,mrp_search_product,stock_cancel,mrp_stock_cancel,stock_orderpoint_manual_procurement,mrp_stock_orderpoint_manual_procurement,web_timeline,mrp_timeline,mrp_timesheet,mrp_timesheet_autofill,mrp_timesheet_calendar,mrp_timesheet_time_control,mrp_timesheet_distribution,procurement_run_manufacture_warnings,mrp_warnings,mrp_workorder_sequence,onchange_helper,partner_academy,partner_contact_access_link,partner_folder,partner_search_city,partner_workflow_dec,payment_transfer,portal_odoo_debranding,procurement_run_mto,procurement_run_mts,procurement_exception,product_active,product_autoset_ok,product_favorite,product_form_purchase_link,product_form_sale_link,product_form_quotation_link,product_legacy_routes,product_order_noname,product_pack_line,stock_move_line_auto_fill,stock_picking_line_auto_fill,purchase_product_pack,product_pack_order_type,product_pricelist_analysis,product_prices_history,product_public_code,tagging,product_tagging,sale_timesheet,product_reference_management,product_reference,product_reference_analytic,product_reference_logging,product_reference_market,product_reference_pack,wizard_run,product_reference_price_history,product_reference_tagging,product_service_no_routes,product_stock,product_supplierinfo,product_template_link,product_template_orderpoints,project_list,project_merge,project_purchase_link,project_report_aeroo,project_task_default_stage,project_task_subtask,project_task_subtask_workflow_dec,project_timesheet_naming,project_timesheet_project_type,project_timesheet_time_rounding,project_workflow_dec,purchase_cancel_propagation,purchase_delivery_rate,purchase_exception,purchase_force_invoiced,purchase_line_procurement_group,purchase_merge,purchase_order_approval_block,purchase_minimum_amount,purchase_order_line_stock_available,purchase_order_stock_picking_link,purchase_responsible_auto,purchase_split,purchase_stock_cancel,purchase_stock_group_empty,stock_return_request,purchase_stock_return_request,purchase_traceability,sale_traceability,purchase_stock_traceability,purchase_supplier,purchase_workflow_dec,remove_odoo_enterprise,report_aeroo_replace_qweb,res_users_signature_hr,sale_row_layout,sale_account_traceability,sale_crm_workflow_dec,sale_delivery_rate,sale_force_invoiced,sale_lockable,sale_markup,sale_mrp_traceability,sale_prices,sale_product_warnings,sale_project_traceability,sale_purchase_traceability,sale_remote,sale_timesheet_existing_project,sale_timesheet_line_exclude,sale_timesheet_purchase,sale_timesheet_task_exclude,sale_workflow_dec,software,software_account,software_license,software_license_dongle,software_license_feature,software_license_keygen,software_license_legacy,software_license_report_aeroo,software_license_token,stock_quantity_history_location,stock_account_quantity_history_location,stock_analysis,stock_notify,stock_orderpoint_auto_multiple,stock_orderpoint_ignore,stock_orderpoint_simulator,stock_orderpoint_unique,stock_picking_invoice_link,stock_picking_purchase_order_link,stock_picking_sale_order_link,stock_report_quantity_by_location,stock_return_routes,stock_sale_traceability,stock_split_procure_method,stock_valuation_default,stock_workflow_dec,uom_smart_search,uom_wide_fix,uom_workflow_dec,web_advanced_search,web_advanced_search_wildcard,web_base_view,web_calendar_options,web_diagram,web_dialog_size,web_edit_user_filter,web_environment_ribbon,web_environment_ribbon_filtering,web_export_view,web_favicon,web_form_orderedby,web_kanban_gauge,web_listview_range_select,web_m2x_options,web_no_bubble,web_notify,web_pdf_preview,web_refresher,web_search_with_and,web_settings_dashboard,website_animate,website_canonical_url,website_form_project,website_form_recaptcha,website_img_dimension,website_logo,website_megamenu,website_odoo_debranding,website_sale_checkout_skip_payment,website_sale_stock,website_sale_delivery,website_sale_hide_empty_category,website_sale_main_category,website_sale_management,website_sale_tax_toggle,website_sale_workflow_dec,website_sale_product_public_code,website_sale_product_style_badge,website_theme_install,website_twitter,website_workflow_dec,web_tree_image_tooltip,web_tree_many2one_clickable,web_tree_resize_column,web_unsplash,web_widget_domain_editor_dialog,web_widget_id,web_widget_numeric_step,web_widget_open_tab,theme_bootswatch
`

**Comment by pedrobaeza** [comment]
You can propose a PR adding such line.
