### ISSUE TITLE
request for migration to v16: web_widget_x2many_2d_matrix 

### ISSUE THREAD

**Issue by ccandito** [OCA/web#2427]
this module is used in several other OCA modules. 
Has its migration been planned please?
regards
Claudio Candito

**Comment by legalsylvain** [comment]
Hi @ccandito. to know if a module is planned to be migrated, you can refer to the Issue related to the version you target. 
For v16, it's here : https://github.com/OCA/web/issues/2309
So you know what is the current status for each module.
Generally, module are migrated, except if the feature is obsolete.

If you have a budget to finance the migration, you can mention it, it will speed up the migration. 
Otherwise, you have to wait !

closing, because there is no problem.
