### ISSUE TITLE
[16.0] web_refresher: Refresh action returns to create a new record when already has been created the record

### ISSUE THREAD

**Issue by kikopeiro** [OCA/web#2836]
## Module

web_refresher

## Describe the bug

Refresh action returns to create a new record when already has been created the record

## To Reproduce
**Affected versions**: checked in v16

1. Create a new record (for example a new partner)
2. Presh de refresh button
3. The record is not refreshed

https://github.com/OCA/web/assets/4610000/66f58758-3b60-4990-b927-3ecf0d1ffc67

**Expected behavior**

The created record should be shown

**Comment by amarcosg** [comment]
This happens in v16 since the backport from v17 from issue https://github.com/OCA/web/pull/2787.

 I tried it in a v17 runbot and it happens there too

https://github.com/user-attachments/assets/572dcb89-4cc3-49a5-98eb-5c8c4d1ca063

This weird refresh happens at the [searchModel.search() ](https://github.com/OCA/web/blob/17.0/web_refresher/static/src/js/refresher.esm.js#L57) call but I don't know what it is for and can't bring myself to touch it without knowing why it is there. 

Migration to [v17](https://github.com/OCA/web/pull/2669) was done by @LazarusUA dont know if he has any idea of a possible fix.

**Comment by TesaLazarenko** [comment]
Hi, I found out about the problem after I was tagged, I'll take a look at it in the next few days and prepare a fix

**Comment by kikopeiro** [comment]
Thanks @LazarusUA !!!
