### ISSUE TITLE
[9.0][10.0] web_responsive conflicts with web_menu_collapsible: Drop down menus don't expand

### ISSUE THREAD

**Issue by dreispt** [OCA/web#556]
Inside an app, you can't access second level menu items. I'm using Firefox 53.0a2.

For example, in the Settings app, click on the "Technical" menu and it won't expand, making it's options unavailable.

![2017-02-15 09_54_57-dashboard - odoo - firefox developer edition](https://cloud.githubusercontent.com/assets/1246629/22969538/c45f2a38-f366-11e6-99ae-f7117142896c.png)

**Comment by pedrobaeza** [comment]
I'm using the same and I have no problem. Check NoScript or similar.

**Comment by pedrobaeza** [comment]
@dreispt I have found what is the problem: _web_menu_collapsible_ is screwing the thing.

I anticipated some kind of overlap, but not conflict in https://github.com/OCA/web/pull/463#issuecomment-258158226, but it totally conflicts.

@tarteo, as your module landed later, please assure the compatibility with web_responsive. I still don't understand why not putting web_responsive and forget all the pains with the fixed sidebar, but anyway...

**Comment by tarteo** [comment]
@pedrobaeza Those modules are not meant to be installed along each other. It's like complaining when 'web_theme_blue' and 'web_theme_green' are conflicting each other (just a metaphor). This will probably only happen in a Runbot installation.

Since you're really convinced about the module not being relevant anymore, please, please, please, just remove the module. I really don't care if the module is in the repository of OCA. I only care for the module to be open source, and available for users to download and install. I'll move it into Onestein's repository so users can still download and enjoy it.

@dreispt Thanks for finding this issue.

**Comment by lasley** [comment]
@tarteo - I'm ok with a completely incompatible modules, it is what it is. We're in a rock and a hard place with testing though, because we definitely can't have two modules conflicting with each other on Runbot.

As a note, I specifically made `web_responsive` compatible with other modules that I did not believe should be installed alongside it so that it can be tested in Runbot along with everything. It was really difficult to achieve that TBH, so I get not wanting to. It may also be downright impossible in this instance.

If your decision is to not support the module installed alongside other modules in this repo, we will need to isolate it from our testing using the Travis file. This will also remove the ability for users to functionally test it on Runbot, which kind of sucks for a UI module IMO.

We also need a very clear note of the incompatibility, likely in both ReadMes. It would be incredibly nice if there was some sort of key we could use in the manifest to notate incompatible addons, but I'm pretty sure that's not a thing.

**Comment by lasley** [comment]
It may also be possible to combine the two modules, allowing for a customizable interface. I don't fully understand what your module does, but if it just hides the left bar - we can probably make that functionality work as an option in `web_responsive`. I didn't get rid of any of the elements, I simply hid them.

**Comment by tarteo** [comment]
@lasley 

> "This will also remove the ability for users to functionally test it on Runbot, which kind of sucks for a UI module IMO"

 If web_menu_collapse is compatible with the web_responsive module there is nothing to test in Runbot anyway. Because I've to totally disable web_menu_collapsible's functionality, or over rule web_responsive's functionality to be compatible with web_responsive.

> "
> It may also be possible to combine the two modules, allowing for a customizable interface. I don't fully understand what your module does, but if it just hides the left bar - we can probably make that functionality work as an option in web_responsive. I didn't get rid of any of the elements, I simply hid them.
> "

web_menu_collapsible makes the second top menu (the purple ones) collapsible which are in the web_responsive module moved to the top bar.

**Proposal:**
It can not be added to the functionality of web_responsive. We can make a module called web_menu with a settings view for all the options (functionalities) of all the menu modules. The menu options when activated will install the correct module (e.g. web_responsive, web_menu_collapsible, ..., ...). And we have to make web_responsive and web_menu_collapsible somehow hidden, so it's only installable via the web_menu module. 
(I don't know if this is possible in Odoo)

**Proposal 2:**
Change the Travis file.

What do you think?

**Comment by pedrobaeza** [comment]
One thing: Travis file is independent from Runbot. Runbot installs everything in the repo, unless you have a whitelist for installing modules. The problem is that runbot doesn't have the possibility right now to blacklist a module, which is what we need here.

**Comment by lasley** [comment]
@pedrobaeza - this is incorrect now that we have Dockerized our Runbot. Travis2Docker uses the first `TESTS=1` that is found in the Travis file matrix, which can contain an exclude statement.

@tarteo - Ohhhhh I really like the centralized menu module installing whatever you actually want. We could then use the exclude statement in Travis file to exclude both of them, then have checking the setting as part of the ReadMe of both modules. It would also allow us to verify that only one is installed at a time, so total win I think!

The flip side is that the exclude statement will not test the modules, so we would need another build in the matrix that doesn't have the exclude. As long as it's lower in the matrix, it will only be used for Travis tests.

**Comment by pedrobaeza** [comment]
OK, I didn't know about the exclude in Travis2docker. Cool then and it can be a solution.
