### ISSUE TITLE
[10.0]Request for using web_notify in the desktop 

### ISSUE THREAD

**Issue by flotho** [OCA/web#723]
Hi,
When sending a message in the chatter on odoo, a message could appear in your notification taskbar. The web_notify module work perfectly but don't seem to send the notif the same way so that the user has to be in front of odoo to see the notif.

Is there a way to implement his? what could it be?

regards

**Comment by hbrunn** [comment]
replace https://github.com/OCA/web/blob/10.0/web_notify/static/src/js/web_client.js#L35 resp https://github.com/OCA/web/blob/10.0/web_notify/static/src/js/web_client.js#L37 with a call to the [javascript notification api](https://developer.mozilla.org/en-US/docs/Web/API/notification). Should be very straightforward. Better not replace but check if you have permission for a desktop notification, if so, do that, otherwise, use what's here already.

But I think it's better to do it the other way around: Provide a module that makes calls to `on_message_*` create a desktop notification (or both depending on configuration) if there's permission.

**Comment by pedrobaeza** [comment]
Closing as it was answered, but no later feedback.
